// Minimal — generated by @web-kits/audio (ESM export)
export const tap = {
    source: { type: "sine", frequency: 1200 },
    envelope: { attack: 0, decay: 0.012, sustain: 0, release: 0.004 },
    gain: 0.08
};

export const click = {
    source: { type: "sine", frequency: 800 },
    envelope: { attack: 0, decay: 0.015, sustain: 0, release: 0.005 },
    gain: 0.1
};

export const keyPress = {
    source: { type: "sine", frequency: 1100 },
    envelope: { attack: 0, decay: 0.01, sustain: 0, release: 0.003 },
    gain: 0.06
};

export const tabSwitch = {
    source: { type: "sine", frequency: 1050 },
    envelope: { attack: 0, decay: 0.015, sustain: 0, release: 0.005 },
    gain: 0.07
};

export const _patch = {
    name: "Minimal",
    author: "Raphael Salaja",
    version: "1.0.0",
    description: "An ultra-clean sine-based palette for quiet, transparent UI feedback, made for products that prioritize subtlety, restraint, and smooth interaction cues over expressive flourish.",
    sounds: { tap, click, "key-press": keyPress, "tab-switch": tabSwitch }
};
